"""记忆存储抽象接口。"""

from __future__ import annotations

from typing import Protocol

from lnagent.memory.models import HotCanon, NovelMeta, SceneSession


class MemoryStore(Protocol):
    def ensure_project_layout(self) -> None: ...

    def load_meta(self) -> NovelMeta: ...

    def save_meta(self, meta: NovelMeta) -> None: ...

    def load_canon(self) -> HotCanon: ...

    def save_canon(self, canon: HotCanon) -> None: ...

    def load_session(self) -> SceneSession: ...

    def save_session(self, session: SceneSession) -> None: ...

    def project_exists(self) -> bool: ...
