"""记忆存储抽象接口。"""

from __future__ import annotations

from typing import Protocol

from lnagent.memory.models import (
    ColdSynopsis,
    HotCanon,
    NovelMeta,
    SceneSession,
    WorldbookStructured,
)


class MemoryStore(Protocol):
    def ensure_project_layout(self) -> None: ...

    def load_meta(self) -> NovelMeta: ...

    def save_meta(self, meta: NovelMeta) -> None: ...

    def load_canon(self) -> HotCanon: ...

    def save_canon(self, canon: HotCanon) -> None: ...

    def load_session(self) -> SceneSession: ...

    def save_session(self, session: SceneSession) -> None: ...

    def append_scene_text(self, scene_id: str, text: str) -> None: ...

    def rewrite_scene_manuscript(self, scene_id: str, content: str) -> None: ...

    def load_synopsis(self) -> ColdSynopsis: ...

    def save_synopsis(self, synopsis: ColdSynopsis) -> None: ...

    def load_worldbook_source(self) -> str: ...

    def save_worldbook_source(self, source: str) -> None: ...

    def load_worldbook_structured(self) -> WorldbookStructured: ...

    def save_worldbook_structured(self, structured: WorldbookStructured) -> None: ...

    def read_scene_manuscript(self, scene_id: str) -> str: ...

    def ensure_scene_manuscript(self, scene_id: str) -> None: ...

    def project_exists(self) -> bool: ...
